### ISSUE TITLE
Not able to paste the address into Config page

### ISSUE THREAD

**Issue by abhi3700** [autonomys/space-acres#145]
## Description
I am not able to paste the address via <kbd>cmd+v</kbd>/<kbd>ctrl+v</kbd> into this screen input textbox.
<img width="803" alt="image" src="https://github.com/subspace/space-acres/assets/16472948/8447bdb9-5cff-4caa-884a-657977eaf6d4">

> I generated the key from my terminal using `sp_core` lib in a rust code.

**Comment by nazar-pc** [comment]
Never had this issue, have you tried pasting it into a text editor to make sure you've actually copied address in the first place?

**Comment by abhi3700** [comment]
Sharing a clip here to show that it's not getting pasted using <kbd>cmd+v</kbd>/<kbd>ctrl+v</kbd> on macOS.



https://github.com/subspace/space-acres/assets/16472948/5047a934-22e7-4acd-9955-657e64300816

**Comment by nazar-pc** [comment]
Are you able to paste things into other fields like farm size? This looks like a GTK4 bug to me.

**Comment by abhi3700** [comment]
> Are you able to paste things into other fields like farm size?
Neither am I able to paste into other fields. Tried with `farm size`.

Also, <kbd>cmd+delete</kbd>/<kbd>ctrl+delete</kbd>/<kbd>opt+delete</kbd> is not working for deleting everything written into textbox.

> This looks like a GTK4 bug to me.
Basically, the shortcut keys are not working.

**Comment by nazar-pc** [comment]
Report this upstream, not much I can do here: https://gitlab.gnome.org/GNOME/gtk

Since we don't have official macOS packages, this is a very low priority to fix.

**Comment by nazar-pc** [comment]
@abhi3700 do you have a link to upstream issue to share?

**Comment by jim-counter** [comment]
I have seen @EmilFattakhov report similar issues I have not experienced myself. I am suspicious this is a MacOS thing.

**Comment by nazar-pc** [comment]
It is macOS thing as labels indicate, someone just needs to report it upstream and maybe even contribute to fixing

**Comment by abhi3700** [comment]
> @abhi3700 do you have a link to upstream issue to share?

I created an issue here: https://github.com/gtk-rs/gtk4-rs/issues/1636. Didn't quite understand what upstream meant as in where to post the issue in this [comment](https://github.com/gtk-rs/gtk4-rs/issues/1636#issuecomment-1981307621).

**Comment by abhi3700** [comment]
> I have seen @EmilFattakhov report similar issues I have not experienced myself on Windows. I am suspicious this is a MacOS thing.

Yes it is.

**Comment by nazar-pc** [comment]
> Didn't quite understand what upstream meant

I literally gave you a link to upstream repository where it should have been reported :confused: 

gtk4-rs is just Rust bindings, it doesn't handle clipboard or anything like that.

**Comment by abhi3700** [comment]
At that time, there was some gitlab server issue, as far as I can remember. So, I went ahead with creating issue on `gtk4-rs` repo.
Created issue on upstream: https://gitlab.gnome.org/GNOME/gtk/-/issues/6559.

Apologies for the delay caused.

**Comment by nazar-pc** [comment]
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7260 was merged, so should be fixed in 4.16, but hopefully also backported into 4.14 stable series.

**Comment by nazar-pc** [comment]
Should be fixed in 0.1.36 with GTK upgrade to 4.16.1
