### ISSUE TITLE
WARN Node: trust_dns_proto::udp::udp_client_stream: ignoring response from [fe80::aeb6:87ff:fe5e:d5aa%12]:53 because it does not match name_server: [fe80::aeb6:87ff:fe5e:d5aa]:53.

### ISSUE THREAD

**Issue by stewfarq** [autonomys/space-acres#178]
I am using v0.1.12 and for over a week I have been getting no rewards even though the consensus node is fully synced.  The log file says the following: WARN Node: trust_dns_proto::udp::udp_client_stream: ignoring response from [fe80::aeb6:87ff:fe5e:d5aa%12]:53 because it does not match name_server: [fe80::aeb6:87ff:fe5e:d5aa]:53.

Running Win11 native.

What is the issue here?

**Comment by nazar-pc** [comment]
That warning is harmless and not related to rewards

**Comment by nazar-pc** [comment]
DNS issues are most likely caused by OS/router/ISP, don't think there is much we can do about it
