### ISSUE TITLE
macOS: Tray icon related issues & more

### ISSUE THREAD

**Issue by abhi3700** [autonomys/space-acres#183]
## Background

This issue is observed on macOS using the `space-acres` version that has this PR #172 merged.

## Issues
There are 3 main issues observed:

1. The tray looks like this on macOS with a different name - "TEST BUTTON":
<img width="802" alt="image" src="https://github.com/subspace/space-acres/assets/16472948/4ffd0347-4b8d-4ed7-9c38-75f18e87a58c">

I don't know where this name is defined 🤔 . Is it in gtk library or somewhere else as I didn't find in `space-acres`'s codebase.

2. I noticed the tray icon goes away when switched to another application. As you can see here in image below that there is no "TEST BUTTON" as tray icon when I switched to browser.
<img width="657" alt="image" src="https://github.com/subspace/space-acres/assets/16472948/5e81c588-1489-4f53-b61a-8ec7dbe57781">

Sometimes the tray icon remains to be seen as I navigate through different apps, but browser. Not sure why this happens particularly in case of browser (may be chromium-based) app, Visual Studio Code (sometimes).
Sharing a clip to show this issue:
https://github.com/subspace/space-acres/assets/16472948/0a31b3a7-81b1-4632-9cfc-2b9e94a8ced9

3. When clicked on this icon as shown in the image below, there are some error logs observed in CLI:
<img width="979" alt="image" src="https://github.com/subspace/space-acres/assets/16472948/f2d8e3c0-bb87-4410-9364-8034dd227829">

Please watch this clip to view the issues:
https://github.com/subspace/space-acres/assets/16472948/0437e78b-d37e-42a0-b4a1-bf0c7a031344

**Comment by hunjixin** [comment]
@abhi3700 
the ```TEST BUTTON``` string define here https://github.com/sidit77/betrayer/blob/1dbe481a0b9512b3357e3a2ea9cb5ff6edac3b89/src/platform/macos/mod.rs#L59.   betray have some test code for macos.  but I think the majority of the work is concentrated in this file.

**Comment by hunjixin** [comment]
for question 2 , I guess the reason is simply that there wasn't enough space in taskbar.

**Comment by abhi3700** [comment]
> https://github.com/sidit77/betrayer/blob/1dbe481a0b9512b3357e3a2ea9cb5ff6edac3b89/src/platform/macos/mod.rs#L59

Okay! thanks for sharing the crate responsible for this.
Based on this, we can then add a task to somehow change "TEST BUTTON" to "Space Acres" or some icon would be even nicer.

I might take this up next as I am using macOS.

- [ ] Change "TEST BUTTON" to "Space Acres" or add some icon instead (to save space).

**Comment by nazar-pc** [comment]
Will likely be solved by https://github.com/subspace/space-acres/issues/222

**Comment by nazar-pc** [comment]
Closing since we have removed old tray icon and it will be fixed once new implementation (likely from https://github.com/autonomys/space-acres/pull/288) lands.
