### ISSUE TITLE
Localisation on the user interface

### ISSUE THREAD

**Issue by jim-counter** [autonomys/space-acres#215]
Add localisation to the Space Acres UI to improve accessibility for non-English speakers. A first draft of the tasks involved:

- [ ] Centralise all UI strings in a single resource file.
- [ ] Provide a mechanism to support multiple string files.
- [ ] Provide a mechanism on the UI or installer to select a particular localisation resource file.

The list above is just a suggestion for an approach. One of the goals here is to make the process of providing a translation resource as simple as possible for the community.

**Comment by nazar-pc** [comment]
> Provide a mechanism on the UI or installer to select a particular localisation resource file.

I think it should simply detect correct language based on OS language and default to English otehrwise.

**Comment by nazar-pc** [comment]
Infrastructure done, just need to pull all of the text contents into translation file.

https://projectfluent.org/fluent/guide/ contains documentation on used syntax.
