### ISSUE TITLE
Subspace-inspired UI theme

### ISSUE THREAD

**Issue by nazar-pc** [autonomys/space-acres#22]
Right now we use default light/dark GTK theme, but it would be nice to make application look more like Subspace.

This needs to start with design guidelines and end with a GTK theme that we can ship with an app and use in place of default styles.

Styling is done with CSS, we might add extra classes on elements if necessary, but maybe even that is not needed.

**Comment by natachadelarosa** [comment]
Hi @nazar-pc can you assign this task to me?

**Comment by nazar-pc** [comment]
Sure, you decided to work on this?

**Comment by natachadelarosa** [comment]
> Sure, you decided to work on this?

Yeah, I want to implement it! I will work on this during the weekend. Thanks for assigning it to me!

**Comment by nazar-pc** [comment]
Any updates here?

**Comment by nazar-pc** [comment]
This is a quite large project I have no intention on tackling any time soon. Closing for now.
