### ISSUE TITLE
Share feedback - Update branding and links

### ISSUE THREAD

**Issue by vexr** [autonomys/space-acres#248]
The 'Share Feedback' link in the hamburger menu currently directs to https://linktr.ee/subspace_network, which still displays the old Subspace org branding. Additionally, two of the four links on this page lead to outdated websites (GitHub and the Forum). Although the redirects are functioning, they should probably be updated.

**Comment by EmilFattakhov** [comment]
Thank you @vexr, great suggestion! Just spun up a new linktree and it should be resolved by [that PR](https://github.com/autonomys/space-acres/pull/249).
