### ISSUE TITLE
Incorrect Initialization Status Message

### ISSUE THREAD

**Issue by vexr** [autonomys/space-acres#266]
While using Space Acres version 0.1.33, I noticed an issue with the initialization status message. The message reads "Initializing farms 1/0...", which appears to be incorrect. Even though farms are indexed starting from 0 internally, the display should start at 1 and increment correctly to show the total number of farms needed to be initialized.

![Screenshot from 2024-08-06 02-26-02](https://github.com/user-attachments/assets/2cbb5605-d1a0-4dc1-a2f0-8098d6c04bac)

**Comment by nazar-pc** [comment]
Yep, does look like a bug, thanks!

**Comment by nazar-pc** [comment]
Fixed in https://github.com/autonomys/space-acres/pull/267
