### ISSUE TITLE
Farm management and the Save button

### ISSUE THREAD

**Issue by jim-counter** [autonomys/space-acres#305]
Space Acres 0.1.36 on Windows.

The Save button does not always light up when a change is made to the farm configuration. This can be reproduced by deleting farms. Hitting Cancel and then re-entering the configuration screen sees the Save button enabled as expected.

Start state (note the Save button is already lit up - maybe from my previous, unsaved attempt to remove farm 0):

![image](https://github.com/user-attachments/assets/2beb5c04-9f37-4b02-9d62-f831b182dccf)

After removing using the "X" button.

![image](https://github.com/user-attachments/assets/90b3e1f8-329f-4149-b387-1971719d38c8)

The Space Acres instance seems in an odd state after first noticing this behaviour which has actually changed while producing the screenshots.

**Comment by nazar-pc** [comment]
Did you delete all farms? I suspect that'd cause `Save` to be deactivated. Is this still an issue in 0.1.38?

Clear step by step reproduction would be ideal.
