### ISSUE TITLE
Acres won't open, no response when clicked.

### ISSUE THREAD

**Issue by zsvvv** [autonomys/space-acres#310]
My computer configuration is an X299 motherboard, an Intel 7960X CPU, a GT 630 graphics card, and a Windows 10 system. During this setup, Acres was running normally. However, after I upgraded the graphics card to a 3080, while everything else remained unchanged, Acres stopped opening and couldn't run. I found that many people in the community have the same issue as me. Could you please advise on how to resolve this?

**Comment by nazar-pc** [comment]
Also make sure you have latest "Visual C++ Redistributable" installed as mentioned in the documentation, it may cause application to not start: https://docs.autonomys.xyz/farming/space-acres/install#step-1-download-and-install-space-acres

**Comment by zsvvv** [comment]
> 另外，请确保您已安装文档中提到的最新“Visual C++ Redistributable”，这可能会导致应用程序无法启动：https://docs.autonomys.xyz/farming/space-acres/install#step-1-download-and-install-space-acres

You're welcome, it's already been resolved!
