### ISSUE TITLE
The GPU is not starting the rendering process

### ISSUE THREAD

**Issue by zsvvv** [autonomys/space-acres#312]
I'm using version 0.1.38 with a 3080 GPU. After the rendering starts, the CPU is fully loaded, but the GPU is not working. What startup parameters should be added to resolve this?
![临时](https://github.com/user-attachments/assets/a773a8ea-9c86-4e1c-b6e4-c516895b21d8)

**Comment by nazar-pc** [comment]
What CPU is it, also can you attach full logs?

BTW I don't think there is a bug here, so such questions are better to be asked on the forum or Discord until it is confirmed to be a bug.

**Comment by zsvvv** [comment]
> 它是什么 CPU，你能附加完整日志吗？
> 
> 顺便说一句，我不认为这里有一个错误，所以最好在论坛或 Discord 上询问此类问题，直到确认它是一个错误。

The CPU is Intel i9 7960X.
[space-acres.log](https://github.com/user-attachments/files/17449557/space-acres.log)

**Comment by nazar-pc** [comment]
The log is truncated due to rotation, can you zip all the log files together so I can see more of what was happening prior?
