### ISSUE TITLE
Farming on Autonomys Mainnet consensus node runs 16 core CPU at 100%

### ISSUE THREAD

**Issue by stewfarq** [autonomys/space-acres#321]
I have just installed Space Acres 0.2.0 with an existing 500Gb farm.  This farm initial plotting is running my CPU (AMD Ryzen 9 7940HS 16 thread) at 100% CPU and it is maxing out the temp of the CPU causing the PC to shutdown.

Plotting at 15.22 sectors/ph.   This will take a full day at max CPU.  Not good.

Is there a way to limit CPU usage?  I am using Win11 and already using Efficiency Mode to try to slow it down.

**Comment by nazar-pc** [comment]
You can reduce CPU usage during plotting in advanced settings of the app, it'll use only half of the CPU that way, which may help with temperature.
