### ISSUE TITLE
Why is the CPU or GPU usage low

### ISSUE THREAD

**Issue by xli-cube** [autonomys/space-acres#331]
![局部截取_20241114_140411](https://github.com/user-attachments/assets/a7fce75d-5987-4b4c-9e1b-74b3cdcfcad1)

**Comment by nazar-pc** [comment]
I'm afraid a single screenshot with no explanation is not really actionable.

Try joining our Discord where a lot of others can try to help you: https://autonomys.xyz/discord
Or post more details on the forum: https://forum.autonomys.xyz/

GitHub is really for engineering discussions and not questions like this.
