### ISSUE TITLE
GUI unable to display

### ISSUE THREAD

**Issue by QWEA0** [autonomys/space-acres#341]
Both versions 0.2.4 and 0.2.8 have this issue
![1732978395184](https://github.com/user-attachments/assets/d9a55715-6c85-4062-a7ef-bb78eef3c63c)
![1732978467045](https://github.com/user-attachments/assets/b4e234bb-9dc6-4e4b-b30f-0c8a40cf8408)

**Comment by QWEA0** [comment]
[space-acres.log](https://github.com/user-attachments/files/17965781/space-acres.log)

**Comment by nazar-pc** [comment]
Looks like it is running internally, but doesn't render things. I have never seen this before myself.
Can you try to update GPU drivers? Do you have a dedicated GPU installed on the system?

**Comment by QWEA0** [comment]
![image](https://github.com/user-attachments/assets/a1ae0768-7f8b-4bf6-8cd5-a5d32f070b94)
Yes, it's running normally, just the GUI screen is white

**Comment by nazar-pc** [comment]
Are you outputting video via 3080 Ti or onboard graphics, have you tried to use onboard graphics? Also if there is an option in BIOS I'd try to disable iGPU and see if it makes a difference.

**Comment by QWEA0** [comment]
After disabling the onboard graphics card, the program returned to normal
