### ISSUE TITLE
Error: ⁨Failed to send config to backend: ⁨send failed because receiver is gone⁩⁩

### ISSUE THREAD

**Issue by Thisca** [autonomys/space-acres#363]
Hello

I just received the error (Error: ⁨Failed to send config to backend: ⁨send failed because receiver is gone⁩⁩) when trying to start SpaceAcres

I need help

![Error Space Acres](https://github.com/user-attachments/assets/f534281a-74c5-4701-8200-69254b400ea8)

[space-acres.log](https://github.com/user-attachments/files/18237972/space-acres.log)

**Comment by nazar-pc** [comment]
Looks like you have issues with Internet:
```
2024-12-24T08:40:10.349947Z  WARN space_acres::frontend::new_version: Failed to check new release error=error sending request for url (https://api.github.com/repos/autonomys/space-acres/releases/latest) url=https://api.github.com/repos/autonomys/space-acres/releases/latest
2024-12-24T08:40:10.520505Z  INFO Node: substrate: 💤 Idle (0 peers), best: #0 (0x6645…21bd), finalized #0 (0x6645…21bd), ⬇ 0 ⬆ 0    
```

No connection to the rest of P2P network, can't check new releases. It will not work under such conditions, it will hard fail to sync.

**Comment by Thisca** [comment]
I have sorted out the internet problem. How can I make the program try again to connect ?

**Comment by nazar-pc** [comment]
Simply exit and start it again

**Comment by Thisca** [comment]
When I close the program and restart it keeps showing the same error. It does not try to reconect

**Comment by nazar-pc** [comment]
Make sure to exit the app from the menu or tray icon, otherwise it'll be minimized instead of actually exiting

**Comment by Thisca** [comment]
Thanks

![Picture Space Acres](https://github.com/user-attachments/assets/08e1e199-976b-48c6-94fa-4c72b5f9247e)

Is it common to take a long time to start syncing ? Just want to make sure because it has some new information on the top part (13/40)

**Comment by Thisca** [comment]
Thanks
