### ISSUE TITLE
[$150 USDC] Show more lines of logs when app is "Stopped with error"

### ISSUE THREAD

**Issue by jfrank-summit** [autonomys/space-acres#58]
Show the last few lines of logs when app stops due to an error. The current message gives limited useful information and requires user to find logs manually to investigate reason for the app stopping.
![image](https://github.com/nazar-pc/space-acres/assets/37932802/43ba7abc-11ab-4113-9bc7-8d02888642a5)

To earn the bounty, ensure your Pull Request (PR) is approved and merged by a Subspace team member. Remember to read [T&C](https://subspace.network/subspace-community-initiative-terms-and-conditions) before submitting your PR.

**Comment by Fiend-Star-666** [comment]
Hi @EmilFattakhov, @jfrank-summit .

Is this task still up for grabs?

**Comment by EmilFattakhov** [comment]
Hey @Fiend-Star-666, absolutely! Assigning it to you!

**Comment by nazar-pc** [comment]
I was thinking to simplify (and reduce bounty) here to simply show a button that opens logs directory (the same we already have in the menu) since in some cases more log lines are needed and sometimes we (developers) will ask users to upload full log file anyway.

**Comment by Fiend-Star-666** [comment]
This change is in development, would update you soon.

**Comment by nazar-pc** [comment]
@Fiend-Star-666 I'm taking over this PR unless you already have the feature done, but didn't open PR yet.

**Comment by nazar-pc** [comment]
@EmilFattakhov I need a link here that I can point a button to for users to get help (Discord, Forum).
I checked our docs and there isn't really a page like that there, so we either need to add it or have something separate where I can point users when they have unexpected issues.

**Comment by EmilFattakhov** [comment]
@nazar-pc this is going to be the link that you can use: https://docs.subspace.network/docs/farming-&-staking/farming/advanced-cli/cli-troubleshooting/#troubleshooting. I just pushed the small update to fix the broken link to the forum and specified what channels to use to ask for support on Discord, lmk if you think we should add some more information over there.

**Comment by nazar-pc** [comment]
That page is good, but it is for CLI users. With Space Acres most users will not set environment variables, at least not without additional hand-holding. I was thinking about something like "here is where you can ask questions and reach out for help to the community" kind of page.

**Comment by nazar-pc** [comment]
Or maybe giving link directly to Discord is fine?

**Comment by EmilFattakhov** [comment]
Let’s start with just a discord link in this case, and I can add a separate section to Space Acres guide once I’m back in a few days.
