### ISSUE TITLE
Suggested UI enhancements for node state

### ISSUE THREAD

**Issue by jim-counter** [autonomys/space-acres#76]
A graph to show best blockheight over the last x (selectable) minutes:

![image](https://github.com/nazar-pc/space-acres/assets/11335994/e3e74df1-a190-447d-bbfc-4a451484628b)

**Comment by nazar-pc** [comment]
Not sure what block height will be useful for, it is monotonically increasing all the time with the same slope

**Comment by jim-counter** [comment]
Until it isn't for some unknown reason. It would give you an immediate indication of when it stopped.

**Comment by nazar-pc** [comment]
I see, you want it to move in real time, so you can see if it gets stuck at some height. That makes much more sense.

**Comment by jim-counter** [comment]
Yes please - like Task Manager CPU usage.

**Comment by nazar-pc** [comment]
Would be nice to see pretty examples of this. I'm not sure just a chart that is growing all the time is a nice way to visualize it. I was thinking maybe columns with number of blocks imported per second, but that is probably not great either. Some visual reference would be nice to have.
