### ISSUE TITLE
Custom advanced option for node & farmer

### ISSUE THREAD

**Issue by Kazuha-Kaedehara** [autonomys/space-acres#94]
For example, if i want to add `--pending-out-connections 100 --out-connections 100` to the farmer, I hope to directly input these parameters in the `Advanced Configuration` through a textbox. Same as the node.

**Comment by nazar-pc** [comment]
While physically possible, I'd like to avoid adding any unnecessary options to the app unless there is no other way. Why would you want to change those options? I'd rather make it unnecessary to change those options in the first place and for things to "just work" instead.

**Comment by nazar-pc** [comment]
> Because mt network is not good enough :(

What is "mt network"?

> So I want to add these parameters to enhance my plotting speed

I see. We are investigating performance of downloading speed in https://github.com/subspace/subspace/issues/2398 and https://github.com/subspace/subspace/issues/2399 will make situation better too. You can always fork the code and build your custom version from "Actions" tab of GitHub Actions, everything is already automated there.

If you need to change low-level parameters, https://github.com/subspace/subspace is likely always be the most flexible, Space Acres is meant to just work out of the box and shouldn't require you to change anything to get a good plotting speed.
