### ISSUE TITLE
Some Farms have no proving performance indicator while text shows they're farming

### ISSUE THREAD

**Issue by Kazuha-Kaedehara** [autonomys/space-acres#98]
Are these farms with no proving performance indicator working?

<img width="387" alt="image" src="https://github.com/nazar-pc/space-acres/assets/95159210/7a975856-a6a4-4f4f-a469-0abe67174f48">

**Comment by nazar-pc** [comment]
It only shows up on farms that had proven something. Until then there is no information to show because actual performance of that farm is not known yet.
